import { AsyncLocalStorage } from "node:async_hooks";
import { readFileSync } from "node:fs";
import path from "node:path";
import { Pool, types } from "pg";
import type { PoolClient, QueryResultRow } from "pg";

const SCHEMA = [
  `CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(20) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at BIGINT NOT NULL,
    email VARCHAR(254) UNIQUE,
    email_verified SMALLINT NOT NULL DEFAULT 0
  )`,
  "CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower ON users (LOWER(username))",
  `CREATE TABLE IF NOT EXISTS sessions (
    token_hash CHAR(64) PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at BIGINT NOT NULL
  )`,
  "CREATE INDEX IF NOT EXISTS sessions_user ON sessions(user_id)",
  `CREATE TABLE IF NOT EXISTS scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    mode VARCHAR(8) NOT NULL,
    amount INTEGER NOT NULL,
    wpm INTEGER NOT NULL,
    raw_wpm INTEGER NOT NULL,
    accuracy INTEGER NOT NULL,
    consistency INTEGER NOT NULL,
    created_at BIGINT NOT NULL
  )`,
  "CREATE INDEX IF NOT EXISTS scores_board ON scores(mode, amount, wpm DESC)",
  "CREATE INDEX IF NOT EXISTS scores_user ON scores(user_id, mode, amount)",
  `CREATE TABLE IF NOT EXISTS races (
    id VARCHAR(8) PRIMARY KEY,
    creator_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    opponent_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    mode VARCHAR(8) NOT NULL,
    amount INTEGER NOT NULL,
    words TEXT NOT NULL,
    kind VARCHAR(8) NOT NULL DEFAULT 'multi',
    invited_user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    rematch_id VARCHAR(8),
    created_at BIGINT NOT NULL,
    start_at BIGINT,
    finished_at BIGINT,
    cancelled SMALLINT NOT NULL DEFAULT 0,
    winner_id INTEGER REFERENCES users(id) ON DELETE SET NULL
  )`,
  "CREATE INDEX IF NOT EXISTS races_creator ON races(creator_id)",
  "CREATE INDEX IF NOT EXISTS races_opponent ON races(opponent_id)",
  "CREATE INDEX IF NOT EXISTS races_invited_user ON races(invited_user_id)",
  "CREATE INDEX IF NOT EXISTS races_winner ON races(winner_id)",
  `CREATE TABLE IF NOT EXISTS race_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    race_id VARCHAR(8) NOT NULL REFERENCES races(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    ready SMALLINT NOT NULL DEFAULT 0,
    correct_chars INTEGER NOT NULL DEFAULT 0,
    typed_chars INTEGER NOT NULL DEFAULT 0,
    words_done INTEGER NOT NULL DEFAULT 0,
    finished_at BIGINT,
    wpm INTEGER,
    raw_wpm INTEGER,
    accuracy INTEGER,
    correct INTEGER,
    incorrect INTEGER,
    extra INTEGER,
    missed INTEGER,
    PRIMARY KEY (race_id, user_id)
  )`,
  "CREATE INDEX IF NOT EXISTS race_players_order ON race_players(race_id, id)",
  "CREATE INDEX IF NOT EXISTS race_players_user ON race_players(user_id)",
  `CREATE TABLE IF NOT EXISTS test_tickets (
    id VARCHAR(64) PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    seed VARCHAR(128) NOT NULL,
    mode VARCHAR(8) NOT NULL,
    amount INTEGER NOT NULL,
    punctuation SMALLINT NOT NULL,
    numbers SMALLINT NOT NULL,
    started_at BIGINT NOT NULL,
    used SMALLINT NOT NULL DEFAULT 0
  )`,
  "CREATE INDEX IF NOT EXISTS test_tickets_user ON test_tickets(user_id, started_at)",
];

export type DbExecutor = Pool | PoolClient;
export type DbValues = Array<string | number | bigint | boolean | Date | null | Buffer | Uint8Array>;

const transactionContext = new AsyncLocalStorage<PoolClient>();
types.setTypeParser(20, (value) => Number(value));

const globalForDb = globalThis as typeof globalThis & {
  __typechazePostgresDb?: Pool;
  __typechazePostgresDbReady?: Promise<void>;
};

function requiredEnv(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`Missing required environment variable: ${name}`);
  return value;
}

function createPool(): Pool {
  const caSetting = requiredEnv("PGSSLROOTCERT");
  const ca = caSetting.includes("-----BEGIN CERTIFICATE-----")
    ? caSetting.replace(/\\n/g, "\n")
    : readFileSync(path.resolve(caSetting), "utf8");

  return new Pool({
    connectionString: requiredEnv("DATABASE_URL"),
    ssl: { ca, rejectUnauthorized: true },
    max: 10,
    idleTimeoutMillis: 30_000,
    connectionTimeoutMillis: 10_000,
  });
}

function getPool(): Pool {
  return (globalForDb.__typechazePostgresDb ??= createPool());
}

export function getDb(): DbExecutor {
  return transactionContext.getStore() ?? getPool();
}

function postgresSql(sql: string): string {
  let index = 0;
  return sql.replace(/\?/g, () => `$${++index}`);
}

async function ensureSchema(): Promise<void> {
  if (!globalForDb.__typechazePostgresDbReady) {
    globalForDb.__typechazePostgresDbReady = (async () => {
      const db = getPool();
      for (const statement of SCHEMA) await db.query(statement);
    })().catch((error: unknown) => {
      globalForDb.__typechazePostgresDbReady = undefined;
      throw error;
    });
  }
  await globalForDb.__typechazePostgresDbReady;
}

export async function queryRows<T extends QueryResultRow>(
  db: DbExecutor,
  sql: string,
  values: DbValues = []
): Promise<T[]> {
  await ensureSchema();
  const result = await db.query<T>(postgresSql(sql), values);
  return result.rows;
}

export async function queryOne<T extends QueryResultRow>(
  db: DbExecutor,
  sql: string,
  values: DbValues = []
): Promise<T | undefined> {
  const rows = await queryRows<T>(db, sql, values);
  return rows[0];
}

export async function execute(
  db: DbExecutor,
  sql: string,
  values: DbValues = []
): Promise<{ affectedRows: number; insertId: number }> {
  await ensureSchema();
  const result = await db.query(postgresSql(sql), values);
  const firstRow = result.rows[0] as { id?: number | string } | undefined;
  return { affectedRows: result.rowCount ?? 0, insertId: Number(firstRow?.id ?? 0) };
}

/** Runs `fn` inside a transaction and rolls it back if it throws. */
export async function transaction<T>(fn: () => Promise<T>): Promise<T> {
  await ensureSchema();
  const db = await getPool().connect();
  let began = false;
  try {
    await db.query("BEGIN");
    began = true;
    const result = await transactionContext.run(db, fn);
    await db.query("COMMIT");
    return result;
  } catch (error) {
    if (began) {
      try {
        await db.query("ROLLBACK");
      } catch (rollbackError) {
        throw new AggregateError([error, rollbackError], "The database transaction and its rollback both failed.");
      }
    }
    throw error;
  } finally {
    db.release();
  }
}
